### ISSUE TITLE
contradicting license terms

### ISSUE THREAD

**Issue by jorol** [DOAJ/doaj-docs#1]
Hi,

I have noticed some contradictions for the attribute `bibjson.license`. This attribute is modelled as `array` (see https: //doaj.github.io/doaj-docs/develop/data_models/Journal), which results in some cases in contradicting license terms. Example:

```json
{
    "bibjson": {
        "license": [
            {
                "NC": false,
                "ND": false,
                "BY": true,
                "type": "CC BY",
                "SA": false,
                "url": "https://creativecommons.org/licenses/by/4.0/"
            },
            {
                "NC": false,
                "ND": false,
                "BY": true,
                "type": "CC BY-SA",
                "SA": true,
                "url": "https://creativecommons.org/licenses/by-sa/4.0/"
            },
            {
                "NC": false,
                "ND": true,
                "BY": true,
                "type": "CC BY-ND",
                "SA": false,
                "url": "https://creativecommons.org/licenses/by-nd/4.0/"
            },
            {
                "NC": true,
                "ND": false,
                "BY": true,
                "type": "CC BY-NC",
                "SA": false,
                "url": "https://creativecommons.org/licenses/by-nc/4.0/"
            },
            {
                "NC": true,
                "ND": false,
                "BY": true,
                "type": "CC BY-NC-SA",
                "SA": true,
                "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
            },
            {
                "NC": true,
                "ND": true,
                "BY": true,
                "type": "CC BY-NC-ND",
                "SA": false,
                "url": "https://creativecommons.org/licenses/by-nc-nd/4.0/"
            }
        ]
    },
    "id": "0a0d846b6aff4a1bb354d8549d08778b"
}
```

The licenses`CC BY` ("remix, transform, and build upon the material for any purpose, **even commercially**") and `CC BY-NC` ("You **may not use** the material for **commercial** purposes") are not compatible. Any idea how to solve this contradictions?

Thanks

**Comment by dommitchell** [comment]
Hi @jorol - thanks for your ticket!

I think what you are seeing can be explained like this:

We only collect license information at the journal level. This means that we ask a journal to indicate all the different licenses available to authors wishing to publish their work in that journal. If you look at that journal's record in DOAJ, you will see that they allow a range of licenses: https://doaj.org/toc/1934-5275

Does that answer your question?

Best, Dom

**Comment by jorol** [comment]
> We only collect license information at the journal level. This means that we ask a journal to indicate all the different licenses available to authors wishing to publish their work in that journal. 

I see. Thanks.
